# Generated by Django 3.1b1 on 2020-07-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200702_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularproduct',
            old_name='product',
            new_name='Товар',
        ),
        migrations.AlterField(
            model_name='product',
            name='coast',
            field=models.PositiveSmallIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dtm_end',
            field=models.DateTimeField(verbose_name='Конец акции'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dtm_start',
            field=models.DateTimeField(verbose_name='Начало акции'),
        ),
    ]
