# Generated by Django 3.1b1 on 2020-07-01 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200702_0130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularproduct',
            options={'verbose_name': 'Популярные товары'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Акции'},
        ),
    ]
