# Generated by Django 3.1b1 on 2020-07-01 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200702_0213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularproduct',
            options={'verbose_name': 'Популярный товар', 'verbose_name_plural': 'Популярные товары'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
    ]
